server:
  type: simple
  applicationContextPath: /scigraph
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: INFO
graphConfiguration:
  location: ../../build_configurations/target/biologicalOntologies
  indexedNodeProperties:
    - category
    - label
    - fragment
  exactNodeProperties:
    - label
    - synonym
  curies:
    'BTO': 'http://purl.obolibrary.org/obo/BTO_'
cypherResources:
  - path: /dynamic/getnodes
    query: |
            MATCH (n)
            where (n.label = {term} AND n.uri =~ ".*(?i)${ontologies_1}#.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_2}#.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_3}#.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_4}#.*") OR
            (n.label = {term} AND n.uri =~ ".*(?i)${ontologies_1}_.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_2}_.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_3}_.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_4}_.*") OR
            (n.label = {term} AND n.uri =~ ".*(?i)${ontologies_1}/.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_2}/.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_3}/.*") OR
            (n.label = {term} AND n.uri =~ "(?i)${ontologies_4}/.*")
            RETURN distinct n
    operations:
      - nickname: get_term_from_particular_ontologies
        summary: Get a term from a specified list of ontologies.  If the first URI is blank all ontologies will be seached.
        parameters:
          - name: term
            description: The term to find # try HP_0000528
            paramType: query
          - name: ontologies_1
            description: An ontology URI from which to search for the terms
            paramType: query
            required: false
            type: string
          - name: ontologies_2
            description: An ontology URI from which to search for the terms
            paramType: query
            required: false
            type: string
          - name: ontologies_3
            description: An ontology URI from which to search for the terms
            paramType: query
            required: false
            type: string
          - name: ontologies_4
            description: An ontology URI from which to search for the terms
            paramType: query
            required: false
            type: string
  - path: /dynamic/xref
    query: |
            MATCH (n)
            where (n.label = {term} AND n.`http://www.geneontology.org/formats/oboInOwl#hasDbXref` IS NOT NULL) 
            RETURN distinct n
    operations:
      - nickname: get_term_from_particular_ontologies
        summary: Display nodes that have an exact term as a label and hasDBXref as a property.
        parameters:
          - name: term
            description: The term to find # try HP_0000528
            paramType: query

serviceMetadata:
  name: 'Pizza Reconciliation Service'
  identifierSpace: 'http://example.org'
  schemaSpace: 'http://example.org'
  view: {
    url: 'http://localhost:9000/scigraph/refine/view/{{id}}'
  }
  preview: {
    url: 'http://localhost:9000/scigraph/refine/preview/{{id}}',
    width: 400,
    height: 400
  }
